### ISSUE TITLE
change zram size/boot from sdcard

### ISSUE THREAD

**Issue by st0nec0ld** [heisath/wdmc2-kernel#16]
Hi, no new issues, just two questions :)

1. It is possible to enlarge /dev/zram0? 49 mb seems very small to me. Could be quickly by 100%.

```
root@wdmycloudhdd:~# df -h
Dateisystem    Größe Benutzt Verf. Verw% Eingehängt auf
/dev/sda3       9,1G    1,1G  7,6G   13% /
devtmpfs        4,0M       0  4,0M    0% /dev
tmpfs           249M       0  249M    0% /dev/shm
tmpfs           100M    1,5M   99M    2% /run
tmpfs           5,0M       0  5,0M    0% /run/lock
/dev/sda2       100G     24K   95G    1% /mnt/data
/dev/zram2      241M     40K  224M    1% /tmp
/dev/zram0       49M     41M  4,1M   91% /var/log
```

2. I try to boot from usb sd card reader instead of usb stick. https://www.amazon.de/gp/product/B009D79VH4

Stick and card reader are detected as sdb device. Exact same build and install procedure for both devices.

Stick
```
Model: SanDisk Extreme (scsi)
Disk /dev/sdb: 64,0GB
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags: 

Number  Start   End     Size    Type     File system  Flags
 1      1049kB  1000MB  999MB   primary  fat32
 2      1000MB  64,0GB  63,0GB  primary  ext4

```

SD Card
```
Model: TS-RDF5A Transcend (scsi)
Disk /dev/sdb: 15,5GB
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags: 

Number  Start   End     Size    Type     File system  Flags
 1      1049kB  1000MB  999MB   primary  fat32
 2      1000MB  15,5GB  14,5GB  primary  ext4
```

Boot from stick works fine. Boot from the card reader don’t, red LED flashes. Interesting fact, boot from card reader works when sda3 has rootfs, with blank/formatted sda3 dont.

Any idea why?

**Comment by Heisath** [comment]
> 1. It is possible to enlarge /dev/zram0? 49 mb seems very small to me. Could be quickly by 100%.

Yeah sure. The zram stuff has been borrowed from Armbian. Their script should include a size.
https://github.com/Heisath/wdmc2-kernel/blob/master/tweaks/etc/default/armbian-ramlog
This would be in /etc/default/ on your device. Original script from: https://github.com/armbian/build

> 2. I try to boot from usb sd card reader instead of usb stick. https://www.amazon.de/gp/product/B009D79VH4

Not entirely sure but SD cards have multiple speeds and accessing modes (SPI, and faster). https://de.wikipedia.org/wiki/SD-Karte#Übertragungsmodi
When experimenting with a SD multiplexing solution, I found that uboot often works fine with the lower speed modes (like SPI) while linux tends to fail because it switches to a higher mode that is not supported by the adapter. This could maybe be fixed via device tree changes.

> Interesting fact, boot from card reader works when sda3 has rootfs, with blank/formatted sda3 dont.

Is it maybe only taking the kernel & ramdisk (which are loaded with uboot) from the sd card and then loading the rootfs from sda3?  See above.

**Comment by st0nec0ld** [comment]
> Yeah sure. The zram stuff has been borrowed from Armbian. Their script should include a size. https://github.com/Heisath/wdmc2-kernel/blob/master/tweaks/etc/default/armbian-ramlog This would be in /etc/default/ on your device. Original script from: https://github.com/armbian/build

Works, thx.
 
> Not entirely sure but SD cards have multiple speeds and accessing modes (SPI, and faster). [https://de.wikipedia.org/wiki/SD-Karte#Übertragungsmodi](https://de.wikipedia.org/wiki/SD-Karte#%C3%9Cbertragungsmodi) When experimenting with a SD multiplexing solution, I found that uboot often works fine with the lower speed modes (like SPI) while linux tends to fail because it switches to a higher mode that is not supported by the adapter. This could maybe be fixed via device tree changes.
> 
 Interessting, is not worth the effort.
